### ISSUE TITLE
Cannot start the container

### ISSUE THREAD

**Issue by aphroz** [pierrefay/docker-magento-zendserver-dev#1]
Hello Pierre,

I followed the instruction on the Readme and when I launch the container here is the output:

sudo ./run-server.sh magento magento.dev
magento
magento
 * Stopping MySQL database server mysqld
   ...done.
 * Starting MySQL database server mysqld
   ...done.
 * Checking for tables which need an upgrade, are corrupt or were 
not closed cleanly.
CLEAR CACHE AND SESSION...
...Installation Complete !
Stopping Zend Server 8.0.2 ..

ERROR 1045 (28000): Access denied for user 'debian-sys-maint'@'localhost' (using password: YES)
zsd is not running
jqd is not running
zdd is not running
scd is not running
lighttpd is not running
 * Stopping web server apache2
 * 
monitor is not running

Zend Server stopped.
Starting Zend Server 8.0.2 ..

Starting Zend Server Monitor node [OK]
[03.07.2015 15:26:19 SYSTEM] watchdog for monitor is running. 
[03.07.2015 15:26:19 SYSTEM] monitor is running. 
 * Starting web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.1. Set the 'ServerName' directive globally to suppress this message
 * 
spawn-fcgi: child spawned successfully: PID: 959
Starting Zend Server GUI [Lighttpd] [OK]
[03.07.2015 15:26:22 SYSTEM] watchdog for lighttpd is running. 
[03.07.2015 15:26:22 SYSTEM] lighttpd is running. 
Starting Session Clustering daemon [OK]
[03.07.2015 15:26:24 SYSTEM] watchdog for scd is running. 
[03.07.2015 15:26:24 SYSTEM] scd is running. 
Starting Deployment [OK]
[03.07.2015 15:26:25 SYSTEM] watchdog for zdd is running. 
[03.07.2015 15:26:25 SYSTEM] zdd is running. 
Starting JobQueue [OK]
[03.07.2015 15:26:26 SYSTEM] watchdog for jqd is running. 
[03.07.2015 15:26:26 SYSTEM] jqd is running. 
Starting ZendServerDaemon [OK]
[03.07.2015 15:26:27 SYSTEM] watchdog for zsd is running. 
[03.07.2015 15:26:27 SYSTEM] zsd is running. 

Zend Server started...

Of course, I am unable to access http://magento.dev

Do I need to first add a database and magento files under /data/magento/ ?

Thank you,

Matias

**Comment by pierrefay** [comment]
Salut Matthias ;)

ca va depuis le weekend open gento ?

t'as bien rajouté " 172.17.0. magento.dev" dans ton fichier host ?

t'as bien fait un git pull avant de lancer ton build ?

Pierre.



2015-07-03 17:33 GMT+02:00 Matias Orlando <notifications@github.com>:

**Comment by aphroz** [comment]
Salut Pierre, 

Oui, ça va bien, merci, comme tu peux le voir j'essayes toujours de faire fonctionner Docker ;)

Le build est up-to-date, mais quand je stope le container j'ai ce message:

Zend Server started...
docker: "inspect" requires a minimum of 1 argument.
See 'docker inspect --help'.

Le fichier host me semble en ordre, et je peux pinger le container aussi.

Merci,

**Comment by pierrefay** [comment]
tu fais docker stop nomducontainer ? et tu as ce message ?

2015-07-06 12:36 GMT+02:00 Matias Orlando <notifications@github.com>:

**Comment by aphroz** [comment]
Je fais:

sudo docker stop <id-container>

Je suis sur un Ubuntu tout neuf si jamais.

**Comment by pierrefay** [comment]
ok essaies :

sudo docker stop <id-container>
sudo docker rm <id-container>

rebuild le container avec --no-cache en option.

et essaie de le relancer ?

**Comment by aphroz** [comment]
ça va pas mieux.. Est-ce que je dois placer les fichiers de Magento quelque part avant de lancer le container?

Si tu veux on peut essayer sur une VM Amazon pour voir si ça passe.

**Comment by pierrefay** [comment]
théoriquement il crée le dossier /data/nomdetonprojet/html et /data/nomdetonprojet/mysql
essai de donner les droits sur le dossier mysql et html en écriture à ton systeme. (chmod 777 -R /data/monprojet/ éventuellement pour tester).

**Comment by pierrefay** [comment]
ensuites tu rajoutes l'ip dans le host (revérifies bien que c'est la même) et normalement tu dois être bon. quand tu accéde en http à ton projet il t'affiche quoi ?

**Comment by aphroz** [comment]
Voici les modifs que j'ai faites dans run-server.sh pour que cela fonctionne:

#!/bin/sh
if [ "$#" -ne 2 ]; then
    echo "Illegal number of parameters use run-server.sh <instance_name> <url_access>"
    return;
fi

#rm -rf /data/$1

echo "killing previous $1 container..."
docker stop $1
docker rm $1
echo "Launching the container..."
docker run --name $1 --env BASE_URL="$2" --env SITE_NAME="$1" -d -v /data/$1/mysql/:/var/lib/mysql -v /data/$1/html/:/var/www/html pierrefay/zendserver-dev-magento

MYHOST="$2"

cp /etc/hosts /etc/hosts_sav

sed -i -e "/$1/d" /etc/hosts

sleep 30s

CONTAINER_ID=$(docker ps | grep "$1 "| awk '{print $1}')
IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $CONTAINER_ID)

echo "$IP www.$2"
echo "$IP www.$2" >> /etc/hosts

echo "Deploying Docker container $1 (http://$MYHOST/) ! Please wait..."

sleep 30s

echo "Container $1 (http://$MYHOST/) started !!"

echo "Server logs - [ctrl + d] to stop :"
tail -f /data/$1/html/logs-server.log

Je suis également en train de rajouter la possibilité d'installer magento directement en rajoutant le paramètre "install" après l'url, ça t'intéresse?

**Comment by pierrefay** [comment]
super :)

Pour installer magento non merci mais c'est gentil de proposer :) Ce container en fait je l'utilise pour importer des projets déjà existants, la toolbar de ZendServer (ZRay) est bien pratique pour étudier un site existant.

Pour faire une demo, j'utilise celui ci : https://github.com/pierrefay/docker-demo-magento 
Faut télécharger les fichiers et les mettre aux bons endroits et maintenant avec Composer etc...ya moyen de tout télécharger et installer plus facilement. Faudra le modifier par la suite  mais tu peux t'en inspirer pour l'installation.
